### ISSUE TITLE
Community centralization

### ISSUE THREAD

**Issue by leojrfs** [crewrktablets/rkflashtools#3]
Hello, 
Would centralizing the rockchip "hackers" community like [linux-sunxi](http://linux-sunxi.org) be a good idea?

let me know if you are available to it.

**Comment by Astralix** [comment]
Hi leojrfs,

thank you for populating the fixes, I'll merge them asap. I tried to centralize the flshtools and I hope I can do that with the other linux tools too. I searched a long time for getting sort of working tools, that's th reason I started this repository.
I have to talk with the other crew members but starting a central launch platform for all active rockchips hackers sounds like a good idea.

regards
Astralix

**Comment by leojrfs** [comment]
lets do it! any irc channel already made that we can use? or we create a new one?

=)

**Comment by leojrfs** [comment]
join #linux-rkx @ freenode

**Comment by Astralix** [comment]
Hey, logged into that channel, and keep it open. Just ping, if I am near my
PC I step in.

Astralix

2013/6/21 Leo Soares notifications@github.com

**Comment by leojrfs** [comment]
#linux-rockchip is replacing the latest ;)

**Comment by Astralix** [comment]
Tells me about needing an invitation...

**Comment by leojrfs** [comment]
sorry, its fixed
